rm = [
  'gry komputerowe);',
  'bezrobocie.',
  'markowych przedmiotów',
  'posiadaniem lepszych wyników w nauce',
  'sporcie',
  'posiadaniem “fajniejszych” przyjaciół;',
  'gry komputerowe)',
  'otępienie',
  'demencja starcza',
  'padaczka',
  'choroba Alzheimera).',
  'obrażanie',
  'groźby',
  'wulgarne słowa',
  'popychanie',
  'bicie laską',
  'plucie',
  'gryzienie',
  'niszczenie przedmiotów.',
  'rozrzucanie przedmiotów',
  'odklejanie opatrunków.',
  'zanieczyszczanie ubrań i pościeli',
  'odmawianie przyjmowania leków',
  'komentarze o podtekście seksualnym',
  'niemoralne propozycje',
  'negliżowanie się',
  'masturbowanie na oczach opiekuna lub presonelu medycznego.',
  'oczernianie pacjenta w obecności personelu medycznego',
  'bielizny)',
  'alkoholu',
  'narkotyków',
  'tlenu',
  'elektrolitów',
  'glukozy',
  'bakterii (posocznica)',
  'rodziny',
  'zamkniętej postawy ciała',
  'wartości',
  'poglądów',
  'gabinecie badań (zbyt głośno',
  'za zimno',
  'za gorąco',
  'tłoczno',
  'ciemno)',
  'gabinetów)',
  '',
  'stosowanie środków odurzających (alkohol',
  'narkotyki)',
  'guzy mózgu',
  'zapalenie mózgu',
  'hipoksja)',
  'aby uzyskać jakieś korzyści np. leki',
  'udawanie dolegliwości',
  'łapówki',
  'Kopnięcie w twarz',
  'Celowe oddawanie moczu poza łóżko',
  'na podłogę ',
  'w ścianę',
  'wózka zabiegowego',
  'kroplówki',
  'wymachiwanie rękami',
  'ciągłe tupanie',
  'nerwowe ruszanie nogą',
  'Tak',
  'Nie',
  'kontuzje',
  'złamania',
  'słaba koncentracja,',
  'alkohol,leki)',
  'diazepam',
  'lub leki przeciwpsychotyczne np. haloperydol);',
  'zadrapania',
  'siniaki',
  'złamanie ręki wkładając je między oparcia łóżka);',
  'Żadnych ',
  'stanowczym głosem',
  'konkretnie na temat;',
  'nie tonem rozkazującym np. Czy mógłby Pan/Pani powiedzieć jak można Panu/Pani pomóc?',
  'empatycznym;',
  'wyrażać stanowczo i spokojnie swoje opinie i prośby',
  'respektując zdanie pacjenta;',
  'nawiązując kontakt z pacjentem',
  'stanąć trochę dalej niż na odległość wyciągniętych ramion;',
  'nożyczki;',
  'Stać zawsze przodem do pacjenta',
  'nie odwracać się ',
  'unikać typowo medycznych nazw;',
  'dać rodzinie czas aby ochłonęła;',
  'nie osądzać;',
  'bieganie',
  'słuchanie muzyki,',
  'imprezy',
  'gry komputerowe);',
  'bezrobocie.',
  'z powodu swoich problemów w domu;',
  'markowych przedmiotów',
  'posiadaniem lepszych wyników w nauce',
  'sporcie',
  'posiadaniem “fajniejszych” przyjaciół;',
  'gry komputerowe)',
  'otępienie',
  'demencja starcza',
  'padaczka',
  'choroba Alzheimera).',
  'obrażanie',
  'groźby',
  'wulgarne słowa',
  'b) Agresja fizyczna- szarpanie',
  'popychanie',
  'bicie laską',
  'plucie',
  'gryzienie',
  'niszczenie przedmiotów.',
  'rozrzucanie przedmiotów',
  'odklejanie opatrunków.',
  'zanieczyszczanie ubrań i pościeli',
  'odmawianie przyjmowania leków',
  'komentarze o podtekście seksualnym',
  'niemoralne propozycje',
  'negliżowanie się',
  'masturbowanie na oczach opiekuna lub presonelu medycznego.',
  'oczernianie pacjenta w obecności personelu medycznego',
  'bielizny)',
  'alkoholu',
  'narkotyków',
  'tlenu',
  'elektrolitów',
  'glukozy',
  'bakterii (posocznica)',
  'rodziny',
  'zamkniętej postawy ciała',
  'wartości',
  'poglądów',
  'gabinecie badań (zbyt głośno',
  'za zimno',
  'za gorąco',
  'tłoczno',
  'ciemno)',
  'gabinetów)',
  'na oddziale)',
  '',
  'stosowanie środków odurzających (alkohol',
  'narkotyki)',
  'guzy mózgu',
  'zapalenie mózgu',
  'hipoksja)',
  'aby uzyskać jakieś korzyści np. leki',
  'udawanie dolegliwości',
  'łapówki',
  'Kopnięcie w twarz',
  'Celowe oddawanie moczu poza łóżko',
  'na podłogę ',
  'wózka zabiegowego',
  'kroplówki',
  'wymachiwanie rękami',
  'ciągłe tupanie',
  'nerwowe ruszanie nogą',
  'Tak',
  'Nie',
  'kontuzje',
  'złamania',
  'słaba koncentracja,',
  'alkohol,leki)',
  'diazepam',
  'lub leki przeciwpsychotyczne np. haloperydol);',
  'zadrapania',
  'siniaki',
  'złamanie ręki wkładając je między oparcia łóżka);',
  'Żadnych ',
  'stanowczym głosem',
  'konkretnie na temat;',
  'nie tonem rozkazującym np. Czy mógłby Pan/Pani powiedzieć jak można Panu/Pani pomóc?',
  'empatycznym;',
  'wyrażać stanowczo i spokojnie swoje opinie i prośby',
  'respektując zdanie pacjenta;',
  'nawiązując kontakt z pacjentem',
  'stanąć trochę dalej niż na odległość wyciągniętych ramion;',
  'nożyczki;',
  'Stać zawsze przodem do pacjenta',
  'nie odwracać się ',
  'unikać typowo medycznych nazw;',
  'dać rodzinie czas aby ochłonęła;',
  'nie osądzać;',
  'bieganie',
  'słuchanie muzyki,',
  'imprezy',
 ]
