columns = [
    'Numer',
    'Płeć',
    'Wiek',
    'Miejsce zamieszkania',
    'Stan cywilny',
    'Występowanie bólu',
    'Wzrost [cm]',
    'Masa ciała [kg]',
    'Staż pracy',
    'Oddział',
    'Dodatkowa praca',
    'Godziny przepracowane w tygodniu',
    'Udogodnienia (w miejscu pracy)',
    'Prawidłowa postawa ciała w pracy',
    'Możliwość planowania przerw',
    'Czy przerwy są wystarczające? (opinia)',
    'Czy środowisko pracy jest zdrowe? (opinia)',
    'Praca pod presją czasu',
    'Czy praca jest wyczerpująca fizycznie? (opinia)',
    'Czy praca jest wyczerpująca psychicznie? (opinia)',
    'Aktywności poza pracą',
    'Od jak dawna wyst. epizody bólowe',
    'Częstotliwość bólu',
    'Utrudnienia w ruchu podczas bólu w czynnościach:',
    'Obowiązki domowe podczas bólu (czy jest w stanie)',
    'Praca zawodowa podczas bólu (czy jest w stanie)',
    'Aktywność fizyczna',
    'Ile minut aktywności fiz. w tyg.',
    'Rodzaj aktywności fizycznej',
    'Czy unika akt. fiz. z obawy przed bólem',
    'Problemy ze snem podczas wyst. bólu',
    'Czy ból uniemożliwiał spotkania towarzyskie',
    'Czy ból powodował obniżenie nastroju',
    'Czy ból pogarsza jakość życia? (opinia)',
    'Ból VAS',
    'Charakter bólu',
    'Kiedy ból mija',
    'Wartość BMI',
    'BMI',
    'Kategoria wiekowa',
    'Rodzaj oddziału',
]
aliases = [
    'N',
    'Sex',
    'Age',
    'Home',
    'Marital',
    'Pain',
    'H',
    'M',
    'Seniority',
    'Branch',
    'Extra',
    'Hours',
    'Comfy',
    'Posture',
    'Breaks',
    'QBreaks',
    'Env',
    'Pressure',
    'PhysExhausting',
    'PsychExhausting',
    'Activity',
    'PainPeriod',
    'PainFreq',
    'MoveProblems',
    'DutyProblems',
    'JobProblems',
    'PhysProblems',
    'ActivityTime',
    'ActivityType',
    'PainMiss',
    'SleepProblems',
    'MeetProblems',
    'MoodProblems',
    'LifeQualityProblems',
    'VAS',
    'PainType',
    'NoPain',
    'BMI',
    'CBMI',
    'CAge',
    'CBranch',
]

c = dict(zip(aliases, columns))
